server:
  port: 8000
spring:
  application:
    name: DB_Master
    config: db_master_config
  cloud:
    nacos:
      config:
        server-addr: 49.232.61.41:8848
        username: nacos
        password: nacos
        file-extension: yml
        context-path: /nacos
        refresh-enabled: true
        enabled: true
  config:
    import: nacos:${spring.application.config}.${spring.cloud.nacos.config.file-extension}
