server:
  port: 8000
spring:
  application:
    name: DB_Master
    config: db_master_config
  cloud:
    nacos:
      config:
        server-addr: 49.232.61.41:8848
        username: nacos
        password: nacos
        file-extension: yml
        context-path: /nacos
        refresh-enabled: true
        enabled: true
  config:
    import: nacos:${spring.application.config}.${spring.cloud.nacos.config.file-extension}
  ai:
    dashscope:
      api-key: sk-56e446c369a241eabd8d2b171ed5bc83
      model: qwen3-4b
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.shuzhi.Controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
  basic:
    enable: true
    username: admin
    password: admin

